from django.urls import path

from app_market.views import (
    CartView,
    CatalogView,
    CategorySlugView,
    ChangeGoodCountInCartView,
    ClearCompareView,
    CompareGoodsView,
    CompareView,
    ContactsView,
    GoodCartView,
    GoodDetailView,
    HistoryDetailOrderView,
    HistoryOrderView,
    IndexView,
    OrderingView,
    PaymentFormView,
    PopularGoodView,
    ProgressPaymentView,
    SaleListView,
    SaleView,
    SellerListView,
    SellerView,
    SuccessfullyView,
    ViewedGoodListView,
    ViewedProductsView,
)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # корзина - добавить-удалить
    path('cart/<str:mtd>/<int:good_id>/', GoodCartView.as_view(), name='good_in_cart'),
    # корзина - изменить количество
    path('cart/change/<str:mtd>/<int:good_id>/<int:count>/',
         ChangeGoodCountInCartView.as_view(),
         name='change_count_in_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('category/<str:slug>/', CategorySlugView.as_view(), name='category'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('catalog/product/<int:pk>/', GoodDetailView.as_view(), name='good_detail'),
    path('compare/add/<int:id>/', CompareView.as_view(), name='add_good_to_compare'),
    path('compare/delete/<int:id>/', ClearCompareView.as_view(), name='delete_good_from_compare'),
    path('compare/clear/', ClearCompareView.as_view(), name='clear_compare'),
    path('compare/view/', CompareView.as_view(), name='view_compare'),
    path('compare/<int:id>/', CompareGoodsView.as_view(), name='compare'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('popular/', PopularGoodView.as_view(), name='popular'),
    path('views/<str:mtd>/<int:good_id>/', ViewedProductsView.as_view(), name='views'),
    path('views/', ViewedGoodListView.as_view(), name='views_list'),
    path('sellers/', SellerListView.as_view(), name='sellers_list'),
    path('sellers/<int:pk>/', SellerView.as_view(), name='seller'),
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/<int:pk>', SaleView.as_view(), name='sale'),
    path('successfully/', SuccessfullyView.as_view(), name='successfully'),
    path('my/checkout/', OrderingView.as_view(), name='ordering'),
    path('my/payment/', PaymentFormView.as_view(), name='payment'),
    path('my/payment/progress/<int:order_id>/', ProgressPaymentView.as_view(), name='payment_status'),
    path('my/orders/', HistoryOrderView.as_view(), name='history_order'),
    path('my/orders/<int:pk>/', HistoryDetailOrderView.as_view(), name='history_detail_order'),
]
