# Generated by Django 3.2.8 on 2021-12-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='relatedgoodgroup',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_discounts', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='relatedgoodgroup',
            name='group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='app_market.goodgroup', verbose_name='Product category 1'),
        ),
        migrations.AddField(
            model_name='relatedgoodgroup',
            name='group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='app_market.goodgroup', verbose_name='Product category 2'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay', to='app_market.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_detail', to='app_market.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='app_market.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_detail', to=settings.AUTH_USER_MODEL, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='goodview',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='views', to='app_market.good', verbose_name='good'),
        ),
        migrations.AddField(
            model_name='goodview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='good', to='app_market.category', verbose_name='Product category'),
        ),
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='good',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='catalog', to='app_market.MediaFiles', verbose_name='related files'),
        ),
        migrations.AddField(
            model_name='good',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='app_market.goodgroup', verbose_name='group of products for discount'),
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good', to='app_market.mediafiles', verbose_name='image for good'),
        ),
        migrations.AddField(
            model_name='good',
            name='tag',
            field=models.ManyToManyField(related_name='good', to='app_market.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='discount',
            name='variants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount', to='app_market.discountvariants', verbose_name='discount options'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='app_market.mediafiles', verbose_name='related files'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_market.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog', to='app_market.delivery', verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog', to='app_market.good', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog', to='app_market.seller', verbose_name='seller'),
        ),
        migrations.AddField(
            model_name='cartsale',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_sale', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='app_market.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='app_market.catalog', verbose_name='catalog_good'),
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='app_market.good', verbose_name='good'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
